##### 머시기미서기임

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('식품_휴게음식점.csv', encoding='cp949', low_memory=False)

In [6]:
df.head()

,개방자치단체코드,관리번호,인허가일자,영업상태명,폐업일자,소재지면적,소재지우편번호,도로명우편번호,사업장명,업태구분명,...,월세액,위생업태명,전통업소주된음식,전통업소지정번호,전화번호,좌표정보(X),좌표정보(Y),지번주소,홈페이지,최종수정시점
0,3000000,3000000-104-2015-00175,2015-10-20,영업/정상,NaN,81.00,110-829,NaN,커피하루,커피숍,...,NaN,커피숍,NaN,NaN,NaN,201909.772207,452439.673216,서울특별시 종로구 숭인동 1400 1층,NaN,2017-08-02 15:38:00
1,3000000,3000000-104-1988-09477,1988-01-14,폐업,2017-02-09,52.78,110-836,3195.0,솔,다방,...,NaN,다방,NaN,NaN,202777420.0,200073.540794,451952.458294,서울특별시 종로구 종로5가 398-7,NaN,2001-11-20 00:00:00
2,3000000,3000000-104-2008-00103,2008-11-26,폐업,2024-09-23,10.43,110-809,3086.0,무비스타,기타 휴게음식점,...,NaN,기타 휴게음식점,NaN,NaN,27652346.0,200247.165180,453407.180093,서울특별시 종로구 동숭동 1-44 인사이드빌딩 지하1층,NaN,2024-09-23 15:59:29
3,3000000,3000000-104-2019-00203,2019-10-18,폐업,2020-06-26,3.30,110-020,3015.0,세븐일레븐 서울상명대점,편의점,...,NaN,편의점,NaN,NaN,232848129.0,196167.247922,455302.372603,서울특별시 종로구 홍지동 72-2,NaN,2020-06-26 10:36:47
4,3000000,3000000-104-2002-00115,2002-12-18,폐업,2011-04-14,14.40,110-522,NaN,델리아띠,다방,...,NaN,다방,NaN,NaN,NaN,200016.479663,453490.041679,서울특별시 종로구 명륜2가 26,NaN,2011-03-28 10:57:11

In [8]:
df.info

<bound method DataFrame.info of         개방자치단체코드                    관리번호       인허가일자  영업상태명        폐업일자  \
0        3000000  3000000-104-2015-00175  2015-10-20  영업/정상         NaN
1        3000000  3000000-104-1988-09477  1988-01-14     폐업  2017-02-09
2        3000000  3000000-104-2008-00103  2008-11-26     폐업  2024-09-23
3        3000000  3000000-104-2019-00203  2019-10-18     폐업  2020-06-26
4        3000000  3000000-104-2002-00115  2002-12-18     폐업  2011-04-14
...          ...                     ...         ...    ...         ...
639213   6520000  6520000-104-2026-00065  2026-05-13  영업/정상         NaN
639214   6520000  6520000-104-2026-00066  2026-05-14  영업/정상         NaN
639215   6520000  6520000-104-2026-00050  2026-04-17  영업/정상         NaN
639216   6520000  6520000-104-2026-00073  2026-06-05     폐업  2026-06-14
639217   6520000  6520000-104-2026-00068  2026-05-26  영업/정상         NaN

         소재지면적  소재지우편번호  도로명우편번호          사업장명     업태구분명  ... 월세액     위생업태명  \
0        81.00  110-829      NaN          커피하루       커피숍  ... NaN       커피숍
1        52.78  110-836   3195.0             솔        다방  ... NaN        다방
2        10.43  110-809   3086.0          무비스타  기타 휴게음식점  ... NaN  기타 휴게음식점
3         3.30  110-020   3015.0  세븐일레븐 서울상명대점       편의점  ... NaN       편의점
4        14.40  110-522      NaN          델리아띠        다방  ... NaN        다방
...        ...      ...      ...           ...       ...  ...  ..       ...
639213   49.87  699-922  63528.0        고양이있어요       커피숍  ... NaN       커피숍
639214  126.59  699-911  63626.0        그라포드커피       커피숍  ... NaN       커피숍
639215   95.10  697-835  63587.0         내향적커피       커피숍  ... NaN       커피숍
639216    9.00  697-858  63546.0          파더스팜        다방  ... NaN        다방
639217   55.30  699-924  63521.0         제주망고당    일반조리판매  ... NaN    일반조리판매

        전통업소주된음식  전통업소지정번호         전화번호        좌표정보(X)        좌표정보(Y)  \
0            NaN       NaN          NaN  201909.772207  452439.673216
1            NaN       NaN  202777420.0  200073.540794  451952.458294
2            NaN       NaN   27652346.0  200247.165180  453407.180093
3            NaN       NaN  232848129.0  196167.247922  455302.372603
4            NaN       NaN          NaN  200016.479663  453490.041679
...          ...       ...          ...            ...            ...
639213       NaN       NaN          NaN  135422.513070  -28531.589250
639214       NaN       NaN          NaN  179357.305672  -20776.666793
639215       NaN       NaN          NaN  160398.880848  -26606.304953
639216       NaN       NaN          NaN  145924.648950  -27829.591775
639217       NaN       NaN          NaN  135071.248638  -23124.555711

                                   지번주소 홈페이지               최종수정시점
0                서울특별시 종로구 숭인동 1400 1층   NaN  2017-08-02 15:38:00
1                 서울특별시 종로구 종로5가 398-7   NaN  2001-11-20 00:00:00
2       서울특별시 종로구 동숭동 1-44 인사이드빌딩 지하1층   NaN  2024-09-23 15:59:29
3                   서울특별시 종로구 홍지동 72-2   NaN  2020-06-26 10:36:47
4                    서울특별시 종로구 명륜2가 26   NaN  2011-03-28 10:57:11
...                                 ...  ...                  ...
639213   제주특별자치도 서귀포시 안덕면 사계리 226 몬트마레   NaN  2026-05-13 11:15:41
639214      제주특별자치도 서귀포시 표선면 토산리 526-3   NaN  2026-05-14 13:13:10
639215          제주특별자치도 서귀포시 동홍동 420-4   NaN  2026-04-17 13:10:58
639216           제주특별자치도 서귀포시 중문동 2642   NaN  2026-06-15 04:15:10
639217       제주특별자치도 서귀포시 안덕면 서광리 1759   NaN  2026-05-27 14:28:25

[639218 rows x 39 columns]>

In [10]:
df.columns.values

<StringArray>
['개방자치단체코드',     '관리번호',    '인허가일자',    '영업상태명',     '폐업일자',    '소재지면적',
  '소재지우편번호',  '도로명우편번호',     '사업장명',    '업태구분명',  '데이터갱신구분',  '건물소유구분명',
 '공장사무직직원수', '공장생산직직원수', '공장판매직직원수',  '급수시설구분명',   '남성종사자수', '다중이용업소여부',
  '데이터갱신시점',    '도로명주소',    '등급구분명',      '보증액',    '본사직원수',  '상세영업상태명',
 '상세영업상태코드',    '시설총규모',   '여성종사자수',   '영업상태코드', '영업장주변구분명',      '월세액',
    '위생업태명', '전통업소주된음식', '전통업소지정번호',     '전화번호',  '좌표정보(X)',  '좌표정보(Y)',
     '지번주소',     '홈페이지',   '최종수정시점']
Length: 39, dtype: str

In [12]:
df_1 = df[['영업상태명', '사업장명', '지번주소']]
df_1

        영업상태명          사업장명                             지번주소
0       영업/정상          커피하루           서울특별시 종로구 숭인동 1400 1층
1          폐업             솔            서울특별시 종로구 종로5가 398-7
2          폐업          무비스타  서울특별시 종로구 동숭동 1-44 인사이드빌딩 지하1층
3          폐업  세븐일레븐 서울상명대점              서울특별시 종로구 홍지동 72-2
4          폐업          델리아띠               서울특별시 종로구 명륜2가 26
...       ...           ...                              ...
639213  영업/정상        고양이있어요   제주특별자치도 서귀포시 안덕면 사계리 226 몬트마레
639214  영업/정상        그라포드커피      제주특별자치도 서귀포시 표선면 토산리 526-3
639215  영업/정상         내향적커피          제주특별자치도 서귀포시 동홍동 420-4
639216     폐업          파더스팜           제주특별자치도 서귀포시 중문동 2642
639217  영업/정상         제주망고당       제주특별자치도 서귀포시 안덕면 서광리 1759

[639218 rows x 3 columns]

In [15]:
df_2 = df_1.dropna(subset=['지번주소'])
df_2

        영업상태명          사업장명                             지번주소
0       영업/정상          커피하루           서울특별시 종로구 숭인동 1400 1층
1          폐업             솔            서울특별시 종로구 종로5가 398-7
2          폐업          무비스타  서울특별시 종로구 동숭동 1-44 인사이드빌딩 지하1층
3          폐업  세븐일레븐 서울상명대점              서울특별시 종로구 홍지동 72-2
4          폐업          델리아띠               서울특별시 종로구 명륜2가 26
...       ...           ...                              ...
639213  영업/정상        고양이있어요   제주특별자치도 서귀포시 안덕면 사계리 226 몬트마레
639214  영업/정상        그라포드커피      제주특별자치도 서귀포시 표선면 토산리 526-3
639215  영업/정상         내향적커피          제주특별자치도 서귀포시 동홍동 420-4
639216     폐업          파더스팜           제주특별자치도 서귀포시 중문동 2642
639217  영업/정상         제주망고당       제주특별자치도 서귀포시 안덕면 서광리 1759

[637394 rows x 3 columns]

In [17]:
df_3 = df_2[ df_2['지번주소'].str.contains('서울특별시')]

In [19]:
df_3

        영업상태명            사업장명                               지번주소
0       영업/정상            커피하루             서울특별시 종로구 숭인동 1400 1층
1          폐업               솔              서울특별시 종로구 종로5가 398-7
2          폐업            무비스타    서울특별시 종로구 동숭동 1-44 인사이드빌딩 지하1층
3          폐업    세븐일레븐 서울상명대점                서울특별시 종로구 홍지동 72-2
4          폐업            델리아띠                 서울특별시 종로구 명륜2가 26
...       ...             ...                                ...
145544     폐업        담초 한시적영업         서울특별시 강동구 천호동 563 동아코아아파트
145545     폐업       사과당 한시적영업  서울특별시 강동구 고덕동 353-23 강동 아이파크 더리버
291080     폐업      쓰리팝(3 POP)               서울특별시 성동구 행당동 19-98
334009     폐업  큰언니네부엌 사회적협동조합            서울특별시 영등포구 영등포동6가 25-5
382802     폐업           소아브카페  경기도 군포시 산본동 1100 서울특별시 남부기술교육원 내

[145355 rows x 3 columns]

In [27]:
df_cu = df_3[ df_3['사업장명'].str.contains('씨유|cu', case = False, na = False)]
df_cu

        영업상태명          사업장명                                지번주소
21      영업/정상       CU종로율곡점           서울특별시 종로구 이화동 80-3 1층 일부
108     영업/정상       씨유 광화문점            서울특별시 종로구 신문로1가 25 정우빌딩
227        폐업       씨유 동묘토성         서울특별시 종로구 숭인동 318-1 1층 101호
281        폐업       씨유 동묘역점                서울특별시 종로구 숭인동 103-1
379     영업/정상  씨유(CU) 동묘토성점                서울특별시 종로구 숭인동 318-1
...       ...           ...                                 ...
145475  영업/정상     씨유 고덕벨리온점       서울특별시 강동구 명일동 46-3 고덕역 대명벨리온
145478  영업/정상       CU천호제일점                서울특별시 강동구 천호동 102-5
145489  영업/정상      씨유 강빛사랑점  서울특별시 강동구 강일동 114 강동리버스트4단지(상가1동)
145500  영업/정상      씨유 강동분홍점                서울특별시 강동구 고덕동 634-2
145502  영업/정상     씨유 암사상암로점               서울특별시 강동구 암사동 491-11

[4050 rows x 3 columns]

In [28]:
df_cu_ing = df_cu[ df_cu['영업상태명'] != '폐업']
df_cu_ing

        영업상태명          사업장명                                지번주소
21      영업/정상       CU종로율곡점           서울특별시 종로구 이화동 80-3 1층 일부
108     영업/정상       씨유 광화문점            서울특별시 종로구 신문로1가 25 정우빌딩
379     영업/정상  씨유(CU) 동묘토성점                서울특별시 종로구 숭인동 318-1
500     영업/정상      씨유 종로2가점                  서울특별시 종로구 관수동 4-4
521     영업/정상       cu종로햇살점                서울특별시 종로구 효제동 248-1
...       ...           ...                                 ...
145475  영업/정상     씨유 고덕벨리온점       서울특별시 강동구 명일동 46-3 고덕역 대명벨리온
145478  영업/정상       CU천호제일점                서울특별시 강동구 천호동 102-5
145489  영업/정상      씨유 강빛사랑점  서울특별시 강동구 강일동 114 강동리버스트4단지(상가1동)
145500  영업/정상      씨유 강동분홍점                서울특별시 강동구 고덕동 634-2
145502  영업/정상     씨유 암사상암로점               서울특별시 강동구 암사동 491-11

[2385 rows x 3 columns]

In [ ]:
df_gs = df_3[ df_3['사업장명'].str.contains('지에스|gs', case = False, na =False)]
df_gs

        영업상태명             사업장명                               지번주소
10      영업/정상        GS25 창신역점          서울특별시 종로구 숭인동 53-21 지상1층
81      영업/정상  지에스(GS)25 종로효제점               서울특별시 종로구 효제동 133-2
188     영업/정상       지에스25 종로sc  서울특별시 종로구 공평동 100 한국스탠다드차타드은행 빌딩
344     영업/정상       지에스25 성대양현           서울특별시 종로구 명륜3가 1-30 102호
353     영업/정상       GS25 종로사직점             서울특별시 종로구 체부동 37-1 1층
...       ...              ...                                ...
145463  영업/정상        GS25 우성스타           서울특별시 강동구 길동 393-7 1층 2호
145477  영업/정상  지에스(GS)25 강동성일점            서울특별시 강동구 성내동 543 화양빌딩
145495  영업/정상      지에스25 암사플러스              서울특별시 강동구 암사동 490-19
145516  영업/정상       GS25천호젠트리스  서울특별시 강동구 성내동 610 힐스테이트 천호역 젠트리스
145518  영업/정상     지에스25 강동센트럴점              서울특별시 강동구 천호동 452-32

[5098 rows x 3 columns]

In [30]:
df_gs_ing = df_gs[ df_gs['영업상태명'] != '폐업']
df_gs_ing

        영업상태명             사업장명                               지번주소
10      영업/정상        GS25 창신역점          서울특별시 종로구 숭인동 53-21 지상1층
81      영업/정상  지에스(GS)25 종로효제점               서울특별시 종로구 효제동 133-2
188     영업/정상       지에스25 종로sc  서울특별시 종로구 공평동 100 한국스탠다드차타드은행 빌딩
344     영업/정상       지에스25 성대양현           서울특별시 종로구 명륜3가 1-30 102호
353     영업/정상       GS25 종로사직점             서울특별시 종로구 체부동 37-1 1층
...       ...              ...                                ...
145463  영업/정상        GS25 우성스타           서울특별시 강동구 길동 393-7 1층 2호
145477  영업/정상  지에스(GS)25 강동성일점            서울특별시 강동구 성내동 543 화양빌딩
145495  영업/정상      지에스25 암사플러스              서울특별시 강동구 암사동 490-19
145516  영업/정상       GS25천호젠트리스  서울특별시 강동구 성내동 610 힐스테이트 천호역 젠트리스
145518  영업/정상     지에스25 강동센트럴점              서울특별시 강동구 천호동 452-32

[2455 rows x 3 columns]

In [25]:
df_seven = df_3[ df_3['사업장명'].str.contains('세븐일레븐', na=False)]
df_seven

        영업상태명            사업장명                                 지번주소
3          폐업    세븐일레븐 서울상명대점                  서울특별시 종로구 홍지동 72-2
138        폐업  세븐일레븐 종로청계천중앙점                  서울특별시 종로구 관철동 37-2
187        폐업    세븐일레븐 상명대제일점                  서울특별시 종로구 홍지동 20-1
258        폐업   세븐일레븐종로르메이에르점  서울특별시 종로구 종로1가 24 르메이에르종로타운1층 101호
298        폐업    세븐일레븐 종로청계천점               서울특별시 종로구 관철동 37-2 1층
...       ...             ...                                  ...
145226  영업/정상     세븐일레븐 강동열린점                서울특별시 강동구 천호동 321-64
145251  영업/정상     세븐일레븐 성일초교점          서울특별시 강동구 성내동 518-13 그린파크빌
145279  영업/정상    세븐일레븐 명일이마트점                  서울특별시 강동구 명일동 47-4
145437  영업/정상    세븐일레븐 한강광나루점                 서울특별시 강동구 천호동 483-8
145479  영업/정상   세븐일레븐 길동엘리아트점         서울특별시 강동구 길동 385-10 영무 엘리아트

[3368 rows x 3 columns]

In [32]:
df_seven_ing = df_seven[ df_seven['영업상태명'] != '폐업']
df_seven_ing

        영업상태명           사업장명                          지번주소
420     영업/정상   세븐일레븐 종로이비스점          서울특별시 종로구 익선동 132-2
608     영업/정상    세븐일레븐 종로묘동점             서울특별시 종로구 묘동 195
663     영업/정상    세븐일레븐 종로코아점     서울특별시 종로구 관철동 13-13 종로코아
1109    영업/정상   세븐일레븐 인왕산파크점             서울특별시 종로구 무악동 60
1352    영업/정상    세븐일레븐 동대문역점          서울특별시 종로구 창신동 154-1
...       ...            ...                           ...
145226  영업/정상    세븐일레븐 강동열린점         서울특별시 강동구 천호동 321-64
145251  영업/정상    세븐일레븐 성일초교점   서울특별시 강동구 성내동 518-13 그린파크빌
145279  영업/정상   세븐일레븐 명일이마트점           서울특별시 강동구 명일동 47-4
145437  영업/정상   세븐일레븐 한강광나루점          서울특별시 강동구 천호동 483-8
145479  영업/정상  세븐일레븐 길동엘리아트점  서울특별시 강동구 길동 385-10 영무 엘리아트

[1595 rows x 3 columns]

In [42]:
# 각 편의점 브랜드 별 데이터 프레임을 하나로 통합!

df_convenient = pd.concat([
    df_cu_ing.assign(brand = 'CU'),
    df_gs_ing.assign(brand = 'GS'),
    df_seven_ing.assign(brand = '7ELEVEN')
])


df_convenient

        영업상태명           사업장명                          지번주소    brand
21      영업/정상        CU종로율곡점     서울특별시 종로구 이화동 80-3 1층 일부        CU
108     영업/정상        씨유 광화문점      서울특별시 종로구 신문로1가 25 정우빌딩        CU
379     영업/정상   씨유(CU) 동묘토성점          서울특별시 종로구 숭인동 318-1        CU
500     영업/정상       씨유 종로2가점            서울특별시 종로구 관수동 4-4        CU
521     영업/정상        cu종로햇살점          서울특별시 종로구 효제동 248-1        CU
...       ...            ...                           ...      ...
145226  영업/정상    세븐일레븐 강동열린점         서울특별시 강동구 천호동 321-64   7ELEVEN
145251  영업/정상    세븐일레븐 성일초교점   서울특별시 강동구 성내동 518-13 그린파크빌   7ELEVEN
145279  영업/정상   세븐일레븐 명일이마트점           서울특별시 강동구 명일동 47-4   7ELEVEN
145437  영업/정상   세븐일레븐 한강광나루점          서울특별시 강동구 천호동 483-8   7ELEVEN
145479  영업/정상  세븐일레븐 길동엘리아트점  서울특별시 강동구 길동 385-10 영무 엘리아트   7ELEVEN

[6435 rows x 4 columns]

In [43]:
# brand 로 그룹화하여 각각의 브랜드 개수 추출
result = df_convenient.groupby('brand').size()

In [45]:
# 한글 폰트 설정
plt.rc('font', family = 'Malgun Gothic')

# - 부호 깨짐 방지
plt.rc('axes', unicode_minus = False)

In [ ]:
plt.bar(result.index, result.values, edgecolor = 'black')