##### 2026.06.26

##### 클래스의 상속

In [2]:
# 사칙연산을 하는 클래스
# => 클래스 이름, 변수, 함수(메서드), 초기화 함수(생성자)
# 클래스의 이름 대문자로 시작 => FourCal
# 캐멀케이스
# 변수 : 두 개
# 함수(메서드) : 설정, +, *, -, /
class FourCal :
    # 클래스의 멤버 : 변수, 메서드
    
    # 초기화 함수 => 변수 초기화
    def __init__(self, first, second) :
        # 인스턴스 변수 생성과 데이터 할당
        self.first = first
        self.second = second
    
    # 메서드를 통해 변수(인스턴스 변수) 를 생성 => 클래스를 통해서 객체로 만들면 변수가
    # 함수 생성 시에 self를 쓰는 이유 => 인스턴스 멤버를 사용하기 위함!
    def setData(self, first, second):
        # 인스턴스 변수 생성과 데이터 할당
        self.first = first
        self.second = second

    def printData(self):
        print(f'first : {self.first}, second : {self.second}')

    def add(self):
        return self.first + self.second
    
    def sub(self) :
        return self.first - self.second
    
    def mul(self) :
        return self.first * self.second
    
    def div(self) :
        try :
            return self.first / self.second
        except ZeroDivisionError :
            print('0으로 나눠줄 수 없습니다.')

In [14]:
# 클래스의 상속 : 새로운 클래스를 만드는 것
# 상속 => 기존 클래스의 멤버들을 받아서 내 것으로 사용
# 오버라이딩 => 메서드를 수정해서 사용, 처리블록을 수정해서 사용
# MoreFourCal : 새로운 클래스 정의 => pow 제곱을 구해주는 함수를 추가, div 메서드 수정
class MoreFourCal(FourCal) :
    # pass
    def pow(self):
        return self.first**self.second
    
    # 오버라이딩 : 함수의 이름과 매개변수는 그대로 유지하고 -> 처리 부분만 수정해서 정의
    def div(self):
        if self.second == 0 :
            return 0
        return self.first/self.second

In [15]:
# cal1 = MoreFourCal()  # 에러!!! => 생성자 호출
cal1 = MoreFourCal(3, 0)

In [16]:
type(cal1)

__main__.MoreFourCal

In [18]:
cal1.printData()

first : 3, second : 0

In [22]:
cal1.pow()

1

In [24]:
cal1.div()

0

##### 모듈

In [28]:
import mod.mod2

In [30]:
import datetime

In [32]:
day1 = datetime.date(2026, 12, 25)

In [33]:
print(day1, type(day1))

2026-12-25 <class 'datetime.date'>

In [36]:
day2 = datetime.date(2026, 6, 26)

In [38]:
print(day1-day2)

182 days, 0:00:00

In [42]:
print(day1.year, day1.month, day1.day)

2026 12 25

In [47]:
import time

In [50]:
time.time()

1782450457.0827692

In [52]:
lt = time.localtime()

In [55]:
print(lt)
print(lt.tm_year)

time.struct_time(tm_year=2026, tm_mon=6, tm_mday=26, tm_hour=14, tm_min=7, tm_sec=55, tm_wday=4, tm_yday=177, tm_isdst=0)
2026

In [57]:
time.ctime()

'Fri Jun 26 14:12:24 2026'

In [60]:
# 난수
import random as r

In [77]:
r.random()  # 0 이상 1 미만의 실수 반환

0.6944307219707115

In [161]:
# 정수 출력
int(r.random()*10+1)  # 0 이상 10 미만 실수 반환

3

In [164]:
int(r.random()*45 +1) # 1~45

8

In [280]:
r.randint(1, 46)

46

In [282]:
list_scores = []
for i in range(0,10) :
    list_scores.append(r.randint(60,100))

print(list_scores)

[84, 86, 92, 96, 89, 82, 81, 65, 67, 78]

In [284]:
r.choice(list_scores)

84

In [286]:
r.sample(list_scores, 3)

[78, 82, 67]

In [288]:
import os

In [290]:
os.getcwd()

'c:\\Users\\EZ\\쉴더스 루키즈\\생성형 AI 활용을 위한 파이썬\\python_project'

In [292]:
os.mkdir('test')

In [294]:
import json

In [297]:
with open('data.json', 'r', encoding='utf-8') as f:
    # str(json) => list(dict):object
    data = json.load(f)
    print(data, type(data))

[{'name': 'COOL', 'age': 25}] <class 'list'>

In [298]:
# list => str
json_str_data = json.dumps(data)
print(json_str_data, type(json_str_data))

[{"name": "COOL", "age": 25}] <class 'str'>

##### 외부 모듈

In [300]:
import numpy as np

In [302]:
# ndarray : 넘파이의 배열
arr = np.array([1, 2, 3, 4, 5])

In [304]:
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>

In [305]:
ones = np.ones((5,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [307]:
# 일련번호로 된 배열 생성
seq1 = np.arange(0, 11, 2)
print(seq1)

[ 0  2  4  6  8 10]

In [310]:
# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
#
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]

In [312]:
# 속성 확인
list_temp = [
    [1,2,3],
    [4,5,6]
]
arr1 = np.array(list_temp)

In [316]:
print(arr1)
print(arr1.shape)   # 배열의 사이즈 : (행, 열)
print(arr1.ndim)    # 배열의 차원
print(arr1.size)    # 전체 요소의 개수
print(arr1.dtype)   # 데이터의 타입

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64

In [318]:
# 배열의 인덱싱과 슬라이싱 => List와 같다!!!
arr2 = np.array([10, 20, 30, 40])

In [322]:
print(arr2[2])
print(arr2[-1])

30
40

In [324]:
print(arr1)
print(arr1[0], type(arr1[0]))
print(arr1[1][2])

[[1 2 3]
 [4 5 6]]
[1 2 3] <class 'numpy.ndarray'>
6

In [326]:
arr3 = np.array([10, 20, 30, 40, 50])

In [331]:
print(arr3[:])
print(arr3[1:4])
print(arr3[1:])
print(arr3[:4])

[10 20 30 40 50]
[20 30 40]
[20 30 40 50]
[10 20 30 40]

In [333]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [337]:
arr[ 0:2, 1:]

array([[2, 3],
       [5, 6]])

In [341]:
# 배열의 연산 : +, *, **
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [348]:
print(arr1 + 10)
print(arr1 * 10)
print(arr2 ** 2)
print(arr1 + arr2)
print(arr1*arr2)

[11 12 13]
[10 20 30]
[16 25 36]
[5 7 9]
[ 4 10 18]

In [350]:
# 배열의 구조 변경 : 1->2, 2-1
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)

In [ ]:
# 1->2
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr, reshaped_arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)

In [354]:
# 2->1
flated_arr = reshaped_arr.flatten()
print(flated_arr)

[1 2 3 4 5 6]

In [363]:
# 필터링
arr = np.array([1,2,3,4,5,6])
filterd_arr = arr[ arr > 3 ]
print(filterd_arr)

[4 5 6]

In [365]:
# 난수를 생성해서 배열 생성
ran_arr1 = np.random.rand(10)
print(ran_arr1, type(ran_arr1))

[0.32541825 0.45412191 0.95618486 0.34740732 0.11683039 0.51829278
 0.55293492 0.73596204 0.95548725 0.19943257] <class 'numpy.ndarray'>

In [366]:
ran_arr2 = np.random.randint(1, 45, size=(5, 6))
print(ran_arr2)

[[29 12  9  9 22 29]
 [43 44 44 30 29 40]
 [ 7 10 16 10 11 12]
 [29 18 15  9  3 23]
 [13  9 39 17  5 24]]

##### Pandas

In [367]:
import pandas as pd

In [369]:
# DataFrame : 2차원 형식의 표 모양으로 데이터 구조를 생성
data = {
    'Name' : ['cool', 'hot', 'king'],
    'Age' : [20, 30, 25]
}
df = pd.DataFrame(data)

In [372]:
print(df)
print(type(df))

   Name  Age
0  cool   20
1   hot   30
2  king   25
<class 'pandas.DataFrame'>

In [374]:
df.head(2)

   Name  Age
0  cool   20
1   hot   30

In [376]:
df.tail(2)

   Name  Age
1   hot   30
2  king   25

In [378]:
# 데이터의 구조
df.shape

(3, 2)

In [380]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [382]:
# 기초 통계 지표 (숫자 데이터)
df.describe()

        Age
count   3.0
mean   25.0
std     5.0
min    20.0
25%    22.5
50%    25.0
75%    27.5
max    30.0

In [385]:
print(df['Age'].sum())
print(df['Age'].mean())

75
25.0

In [387]:
data = {
    'name' : ['cool', 'hot', 'king'],
    'age' : [20, 30, 25],
    'score' : [90, 70, 60]
}

df = pd.DataFrame(data)

In [389]:
df

   name  age  score
0  cool   20     90
1   hot   30     70
2  king   25     60

In [394]:
df[['name','score']]

   name  score
0  cool     90
1   hot     70
2  king     60

In [396]:
df['passed'] = df['score'] >= 70

In [398]:
df

   name  age  score  passed
0  cool   20     90    True
1   hot   30     70    True
2  king   25     60   False

In [400]:
df[['name', 'passed']]

   name  passed
0  cool    True
1   hot    True
2  king   False

In [402]:
df

   name  age  score  passed
0  cool   20     90    True
1   hot   30     70    True
2  king   25     60   False

In [404]:
df.loc[2, 'score'] = 80

In [405]:
df

   name  age  score  passed
0  cool   20     90    True
1   hot   30     70    True
2  king   25     80   False

In [415]:
df['passed'] = df['score'] >= 60

In [418]:
df.loc[1, 'score'] = None

In [409]:
df

   name  age  score  passed  passwd
0  cool   20     90    True    True
1   hot   30     70    True    True
2  king   25     80   False    True

In [412]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      str
 1   age     3 non-null      int64
 2   score   3 non-null      int64
 3   passed  3 non-null      bool
 4   passwd  3 non-null      bool
dtypes: bool(2), int64(2), str(1)
memory usage: 210.0 bytes

In [416]:
df.describe()

        age  score
count   3.0    3.0
mean   25.0   80.0
std     5.0   10.0
min    20.0   70.0
25%    22.5   75.0
50%    25.0   80.0
75%    27.5   85.0
max    30.0   90.0

In [420]:
df.isnull()

    name    age  score  passed  passwd
0  False  False  False   False   False
1  False  False   True   False   False
2  False  False  False   False   False

In [422]:
# 결측치에 특정값을 저장
df['score'] = df['score'].fillna(100)

In [424]:
df

   name  age  score  passed  passwd
0  cool   20   90.0    True    True
1   hot   30  100.0    True    True
2  king   25   80.0    True    True

In [428]:
df.to_csv('output.csv', index = False)

In [433]:
data_csv = pd.read_csv('output.csv')

In [434]:
data_csv

   name  age  score  passed  passwd
0  cool   20   90.0    True    True
1   hot   30  100.0    True    True
2  king   25   80.0    True    True
3  oreo   50   50.0   False   False