데이터 전처리 EX-5

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv('winequality-red.csv')
df

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [ ]:
# 스케일링할 컬럼명 정의
columns = [
    'fixed acidity', 'volatile acidity',
    'citric acid', 'residual sugar', 'chlorides'
]

# '컬럼명_scaled' 컬럼을 생성하고 스케일링 결과 저장
for column in columns :
    scaler = StandardScaler()
    df[f'{column}_scaled'] = scaler.fit_transform(df[[column]])

df

      fixed acidity  volatile acidity  ...  residual sugar_scaled  chlorides_scaled
0               7.4             0.700  ...              -0.453218         -0.243707
1               7.8             0.880  ...               0.043416          0.223875
2               7.8             0.760  ...              -0.169427          0.096353
3              11.2             0.280  ...              -0.453218         -0.264960
4               7.4             0.700  ...              -0.453218         -0.243707
...             ...               ...  ...                    ...               ...
1594            6.2             0.600  ...              -0.382271          0.053845
1595            5.9             0.550  ...              -0.240375         -0.541259
1596            6.3             0.510  ...              -0.169427         -0.243707
1597            5.9             0.645  ...              -0.382271         -0.264960
1598            6.0             0.310  ...               0.752894         -0.434990

[1599 rows x 17 columns]