데이터 전처리 EX-2

In [2]:
import pandas as pd

In [4]:
# 1. 가짜 데이터 생성
data = {
    'ProductID': [101, 102, 103, 104, 101, 102, 103, 105, 106, 101],
    'ProductName': ['A', 'B', 'C', 'D', 'A', 'B', 'C', 'E', 'F', 'A'],
    'Price': [100, 200, 300, 400, 100, 200, 300, 500, 600, 100],
    'Quantity': [1, 2, 3, 4, 1, 2, 3, 5, 6, 1]
}

# 2. DataFrame 생성
df = pd.DataFrame(data)

# 3. 중복된 데이터를 일부 추가 (중복된 행 4개 추가)
df.loc[len(df.index)] = [101, 'A', 100, 1]  # 중복 행 추가
df.loc[len(df.index)] = [102, 'B', 200, 2]  # 중복 행 추가
df.loc[len(df.index)] = [103, 'C', 300, 3]  # 중복 행 추가
df.loc[len(df.index)] = [104, 'D', 400, 4]  # 중복 행 추가

# 4. CSV 파일로 내보내기
df.to_csv('sales.csv', index=False)

print("sales.csv 파일이 생성되었습니다.")

sales.csv 파일이 생성되었습니다.

In [28]:
df = pd.read_csv('sales.csv')
df

    ProductID ProductName  Price  Quantity
0         101           A    100         1
1         102           B    200         2
2         103           C    300         3
3         104           D    400         4
4         101           A    100         1
5         102           B    200         2
6         103           C    300         3
7         105           E    500         5
8         106           F    600         6
9         101           A    100         1
10        101           A    100         1
11        102           B    200         2
12        103           C    300         3
13        104           D    400         4

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    14 non-null     int64
 1   ProductName  14 non-null     str
 2   Price        14 non-null     int64
 3   Quantity     14 non-null     int64
dtypes: int64(3), str(1)
memory usage: 580.0 bytes

In [ ]:
print(df.duplicated().sum())
print(df[df.duplicated()])

0     False
1     False
2     False
3     False
4      True
5      True
6      True
7     False
8     False
9      True
10     True
11     True
12     True
13     True
dtype: bool
8
    ProductID ProductName  Price  Quantity
4         101           A    100         1
5         102           B    200         2
6         103           C    300         3
9         101           A    100         1
10        101           A    100         1
11        102           B    200         2
12        103           C    300         3
13        104           D    400         4

In [ ]:
# 기본 keep값이 first 이므 첫 번째 중복 데이터는 남기고 제거
df = df.drop_duplicates()
df

   ProductID ProductName  Price  Quantity
0        101           A    100         1
1        102           B    200         2
2        103           C    300         3
3        104           D    400         4
7        105           E    500         5
8        106           F    600         6

In [ ]:
# 제거 후 df에 중복된 데이터의 개수 확인
print(df.duplicated().sum())

0